version: '3.8'

services:
  db:
    image: postgres:16.3
    container_name: social-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: social
    ports:
      - "5432:5432"
    volumes:
      # Persists data on the host machine
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
